UPDATE "orders"
SET order_type = $2,
   relation_id = $3,
   payment_type = $4,
   updated_by = $5,
   total = $6,
   dp = $7,
   payment = $8,
   remain = $9,
   invoice_id = $10,
   due_at = $11,
   created_at = $12,
   updated_at = now()
WHERE id = $1
RETURNING id,
   order_type as "order_type: OrderType",
   relation_id,
   payment_type as "payment_type: PaymentType",
   updated_by,
   total,
   dp,
   payment,
   remain,
   invoice_id,
   due_at,
   created_at,
   updated_at
