UPDATE "orders" SET
        order_type = $2,
        relation_id = $3,
        payment_type = $4,
        updated_by = $5,
        total = $6,
        payment = $7,
        remain = $8,
        invoice_id = $9,
        due_at = $10,
        created_at = $11,
        updated_at = now()
    WHERE id = $1
    RETURNING id,
        order_type as "order_type: OrderType",
        relation_id,
        payment_type as "payment_type: PaymentType",
        updated_by,
        total,
        payment,
        remain,
        invoice_id,
        due_at,
        created_at,
        updated_at
